[package]
name = "fpa"
version = "0.1.0"
authors = ["Jorge Aparicio <japaricious@gmail.com>"]

[dependencies]
numtoa = "0.0.7"

[dependencies.cast]
default-features = false
version = "0.2.0"

[features]
const-fn = []